# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 11:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publishdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
